### PR TITLE
chore: Turn off all the dev guff when going live on production.

### PR DESCRIPTION
**Pull request by cafuego**
Bit odd this was not in the starterkit :-/

Refs: OPS-9471

### CODE REVIEW

**Comment by cafuego** [comment]
These cvhanges are all done manually on production already; this PR just means they do not get reverted on deploy.

**Review by rupl — APPROVED** [review]
I think this works for prod, but on my local the second config import fails because `devel` won't be enabled, but there are pieces of config that depend on it.

- devel.settings
- devel.toolbar.settings

I added `core.extension.yml` to the `config_dev_ dir and am now approving of my fix.

**Comment by cafuego** [comment]
@rupl In theory the change I added in https://github.com/UN-OCHA/whd-2023-site/commit/4e0930b49e3e8c8e9a959d1e837116e2db7f1885 should mean that whole copy of core.extensions.yml isn't needed (I removed it from the PR)

**Comment by rupl** [comment]
Neato, good to know 👍🏼

**Pull request merged**
